ingress-nginx:
  controller:
    nodeSelector:
      kubernetes.io/hostname: "bou001"

  config:
    compute-full-forwarded-for: "true"
    large-client-header-buffers: "4 64k"
    proxy-body-size: "100m"
    proxy-buffer-size: "64k"
    ssl-redirect: "true"
    use-forwarded-headers: "true"
  service:
    externalTrafficPolicy: Local
  podLabels:
    gafaelfawr.lsst.io/ingress: "true"
    hub.jupyter.org/network-access-proxy-http: "true"

vault_certificate:
  enabled: true
  path: secret/k8s_operator/dboutigny.freeboxos.fr/ingress-nginx

pull-secret:
  enabled: true
  path: secret/k8s_operator/dboutigny.freeboxos.fr/pull-secret
