nublado:
  pull_secret: 'pull-secret'
  fqdn: rsp-lapp.ddns.net

  oauth_provider: 'jwt'

  hub:
    image: 'lsstsqre/sciplat-hub:latest'

  wf:
    ingress_ui:
      annotations:
        nginx.ingress.kubernetes.io/auth-method: GET
        nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-Token
        nginx.ingress.kubernetes.io/auth-signin: "https://rsp-lapp.ddns.net/login"
        nginx.ingress.kubernetes.io/auth-url: "http://gafaelfawr-service.gafaelfawr.svc.cluster.local:8080/auth?scope=exec:notebook"
        nginx.ingress.kubernetes.io/configuration-snippet: |
          proxy_set_header X-Forwarded-Proto https;
          proxy_set_header X-Forwarded-Port 443;
          proxy_set_header X-Forwarded-Path /workflow;
          auth_request_set $auth_token $upstream_http_x_auth_request_token;
          proxy_set_header X-Portal-Authorization "Bearer $auth_token";
          error_page 403 = "/auth/forbidden?scope=exec:notebook";

  lab:
    restrict_nodes: 'true'
    image:
      experimentals: 0
      dailies: 0
      releases: 0
      weeklies: 1
      cachefile: '/home/jovyan/repo-cache.json'

    resources:
      nodejs_max_mem: '6144'
      mb_per_cpu: 2048

  routes:
    soda: '/api/image/soda'
    external:
      instance: 'https://rsp-lapp.ddns.net'

  dask:
    restrict_nodes: 'true'

  vault_secrets:
    enabled: true
    path: secret/k8s_operator/rsp-lapp/nublado

  proxy:
    ingress:
      annotations:
        nginx.ingress.kubernetes.io/auth-request-redirect: $request_uri
        nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-Token
        nginx.ingress.kubernetes.io/auth-signin: "https://rsp-lapp.ddns.net/login"
        nginx.ingress.kubernetes.io/auth-url: "http://gafaelfawr-service.gafaelfawr.svc.cluster.local:8080/auth?scope=exec:notebook"
        nginx.ingress.kubernetes.io/configuration-snippet: |
          proxy_set_header X-Forwarded-Proto https;
          proxy_set_header X-Forwarded-Port 443;
          proxy_set_header X-Forwarded-Path /nb;
          auth_request_set $auth_token $upstream_http_x_auth_request_token;
          proxy_set_header X-Portal-Authorization "Bearer $auth_token";
          error_page 403 = "/auth/forbidden?scope=exec:notebook";
      host: rsp-lapp.ddns.net
      tls:
        cluster_issuer: cert-issuer-letsencrypt-dns
        secret: nublado-tls-secret
        tls_host: rsp-lapp.ddns.net

  mountpoints: |
    [
      { "disabled": true,
        "mountpoint": "/example -- if it doesn't start with '/' we add it",
        "fileserver-host": "omit to use Hub settings",
        "fileserver-export": "defaults to '/exports<mountpoint>'",
        "hostpath": "if you're doing direct host mounts, e.g. GPFS w/o NFS",
        "mode": "rw or ro, defaults to 'ro'",
        "options": "mount options, e.g. 'local_lock=all'"
      },
      {
        "mountpoint": "/data",
        "mode": "rw",
        "fileserver-host": "192.168.0.64",
        "fileserver-export": "/data"
      },
      {
        "mountpoint": "/home",
        "mode": "rw",
        "fileserver-host": "192.168.0.64",
        "fileserver-export": "/home"
      }
    ]

pull-secret:
  enabled: true
  path: secret/k8s_operator/rsp-lapp/pull-secret
