nublado2:
  jupyterhub:
    debug:
      enabled: true

    hub:
      image:
        name: lsstsqre/nublado2
        tag: "1.0.0"

    singleuser:
      storage:
        type: none

    ingress:
      hosts: ["dboutigny.freeboxos.fr"]
      annotations:
        nginx.ingress.kubernetes.io/auth-signin: "https://dboutigny.freeboxos.fr/login"

  config:
    base_url: "dboutigny.freeboxos.fr/"

  vault_secret_path: "secret/k8s_operator/dboutigny.freeboxos.fr/nublado2"
  gafaelfawr_secret_path: "secret/k8s_operator/dboutigny.freeboxos.fr/gafaelfawr"