nublado2:
  jupyterhub:
    debug:
      enabled: true

    hub:
      image:
        name: lsstsqre/nublado2
        tag: "1.0.0"

    singleuser:
      storage:
        type: none

    ingress:
      hosts: ["rsp.lapp.in2p3.fr"]
      annotations:
        nginx.ingress.kubernetes.io/auth-signin: "https://rsp.lapp.in2p3.fr/login"

  config:
    base_url: "rsp.lapp.in2p3.fr/"

  vault_secret_path: "secret/k8s_operator/rsp-lapp/nublado2"
  gafaelfawr_secrets_path: "secret/k8s_operator/rsp-lapp/gafaelfawr"



