nublado2:
  jupyterhub:
    debug:
      enabled: true

    hub:
      base_url: "/nb2"

    singleuser:
      storage:
        type: none

    ingress:
      hosts: ["rsp.lapp.in2p3.fr"]
      annotations:
        nginx.ingress.kubernetes.io/auth-signin: "https://rsp.lapp.in2p3.fr/login"

  config:
    base_url: "https://rsp.lapp.in2p3.fr/"
    lab_environment:
      TURN_ON_MONEYPENNY: 'true'
      enable_moneypenny: 'true'

    volumes:
      - name: data
        nfs:
          path: /var/nfsdir/data
          server: 134.158.100.202
      - name: home
        nfs:
          path: /var/nfsdir/jhome
          server: 134.158.100.202

    volume_mounts:
      - name: data
        mountPath: /data
      - name: home
        mountPath: /home


  vault_secret_path: "secret/k8s_operator/rsp-lapp/nublado2"
  gafaelfawr_secrets_path: "secret/k8s_operator/rsp-lapp/gafaelfawr"




